version: "3.9"
name: opentelemetry-services
configs:
  prometheus_config:
    file: prometheus.yml

services:
  # opentelemetry-api:
  #   image: ${DOCKER_REGISTRY-}opentelemetry-api
  #   build:
  #     context: ../src/OpenTelemetryExample.Api
  #     dockerfile: Dockerfile
  #   ports:
  #     - 5000:80
  #   networks:
  #     - opentelemetry
  # opentelemetry-web:
  #   image: ${DOCKER_REGISTRY-}opentelemetry-web
  #   build:
  #     context: ../src/OpenTelemetryExample.Web
  #     dockerfile: Dockerfile
  #   ports:
  #     - 5001:80
  #   networks:
  #     - opentelemetry
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - opentelemetry
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    container_name: prometheus
    networks:
      - opentelemetry
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    networks:
      - opentelemetry

networks:
  opentelemetry:
    name: opentelemetry-network