version: "3.9"
configs:
  prometheus_config:
    file: prometheus.yml

services:
  opentelemetry01:
    image: ${DOCKER_REGISTRY-}opentelemetry01
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 5000:80
    networks:
      - balusoft
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - balusoft
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    container_name: prometheus
    networks:
      - balusoft

networks:
  balusoft:
    name: balusoft-network